// Generated by `npm run i18n:sync` — imports every translation file of this
// locale. Edit the JSON files, not this one.
import f_case_studies from "./case-studies.json";
import f_hubs_advertising from "./hubs/advertising.json";
import f_hubs_branding_creative from "./hubs/branding-creative.json";
import f_hubs_business_local_presence from "./hubs/business-local-presence.json";
import f_hubs_food_restaurants from "./hubs/food-restaurants.json";
import f_hubs_social_media from "./hubs/social-media.json";
import f_hubs_video_production from "./hubs/video-production.json";
import f_hubs_villas_real_estate from "./hubs/villas-real-estate.json";
import f_hubs_websites_digital from "./hubs/websites-digital.json";
import f_industries_brands_lifestyle from "./industries/brands-lifestyle.json";
import f_industries_events from "./industries/events.json";
import f_industries_hotels_resorts from "./industries/hotels-resorts.json";
import f_industries_restaurants_food from "./industries/restaurants-food.json";
import f_industries_tourism_hospitality from "./industries/tourism-hospitality.json";
import f_industries_villas_real_estate from "./industries/villas-real-estate.json";
import f_industries_wellness_retreats from "./industries/wellness-retreats.json";
import f_journal from "./journal.json";
import f_locations_koh_phangan from "./locations/koh-phangan.json";
import f_locations_koh_samui from "./locations/koh-samui.json";
import f_locations_koh_tao from "./locations/koh-tao.json";
import f_pages from "./pages.json";
import f_services_advertising from "./services/advertising.json";
import f_services_branding from "./services/branding.json";
import f_services_commercial_photography from "./services/commercial-photography.json";
import f_services_commercial_video from "./services/commercial-video.json";
import f_services_content_creation from "./services/content-creation.json";
import f_services_digital_marketing from "./services/digital-marketing.json";
import f_services_google_ads from "./services/google-ads.json";
import f_services_meta_ads from "./services/meta-ads.json";
import f_services_restaurant_marketing from "./services/restaurant-marketing.json";
import f_services_seo from "./services/seo.json";
import f_services_social_media_management from "./services/social-media-management.json";
import f_services_villas_real_estate from "./services/villas-real-estate.json";
import f_services_web_design from "./services/web-design.json";
import f_ui from "./ui.json";

const translations = {
  files: {
    "case-studies.json": f_case_studies,
    "hubs/advertising.json": f_hubs_advertising,
    "hubs/branding-creative.json": f_hubs_branding_creative,
    "hubs/business-local-presence.json": f_hubs_business_local_presence,
    "hubs/food-restaurants.json": f_hubs_food_restaurants,
    "hubs/social-media.json": f_hubs_social_media,
    "hubs/video-production.json": f_hubs_video_production,
    "hubs/villas-real-estate.json": f_hubs_villas_real_estate,
    "hubs/websites-digital.json": f_hubs_websites_digital,
    "industries/brands-lifestyle.json": f_industries_brands_lifestyle,
    "industries/events.json": f_industries_events,
    "industries/hotels-resorts.json": f_industries_hotels_resorts,
    "industries/restaurants-food.json": f_industries_restaurants_food,
    "industries/tourism-hospitality.json": f_industries_tourism_hospitality,
    "industries/villas-real-estate.json": f_industries_villas_real_estate,
    "industries/wellness-retreats.json": f_industries_wellness_retreats,
    "journal.json": f_journal,
    "locations/koh-phangan.json": f_locations_koh_phangan,
    "locations/koh-samui.json": f_locations_koh_samui,
    "locations/koh-tao.json": f_locations_koh_tao,
    "pages.json": f_pages,
    "services/advertising.json": f_services_advertising,
    "services/branding.json": f_services_branding,
    "services/commercial-photography.json": f_services_commercial_photography,
    "services/commercial-video.json": f_services_commercial_video,
    "services/content-creation.json": f_services_content_creation,
    "services/digital-marketing.json": f_services_digital_marketing,
    "services/google-ads.json": f_services_google_ads,
    "services/meta-ads.json": f_services_meta_ads,
    "services/restaurant-marketing.json": f_services_restaurant_marketing,
    "services/seo.json": f_services_seo,
    "services/social-media-management.json": f_services_social_media_management,
    "services/villas-real-estate.json": f_services_villas_real_estate,
    "services/web-design.json": f_services_web_design,
    "ui.json": f_ui,
  } as Record<string, unknown>,
};

export default translations;
