/**
 * The one place the site reads localized content from. Every page, block,
 * nav menu and breadcrumb goes through these getters, so editing a string
 * in `src/content/locales/<locale>/*.json` changes it everywhere it's
 * shown. English (the TS files in `src/content/`) is the master and the
 * fallback for anything missing — see `localize.ts` for the merge rules
 * and docs/i18n.md for the editing workflow.
 */
import { DEFAULT_LOCALE, type Locale } from "./i18n";
import { localize } from "./localize";
import { UI, type UiStrings } from "./ui";
import { HUBS } from "./hubs";
import { HOMEPAGE, HOMEPAGE_PILLARS, HOMEPAGE_PORTFOLIO } from "./homepage";
import {
  ABOUT_PAGE,
  CASE_STUDIES_PAGE,
  CONTACT_PAGE,
  JOURNAL_PAGE,
  PORTFOLIO_PAGE,
  PRIVACY_PAGE,
  TERMS_PAGE,
  SERVICES_INDEX,
  INDUSTRIES_INDEX,
  LOCATIONS_INDEX,
  EDITORIAL_PAGE,
  ACCESSIBILITY_PAGE,
  NOT_FOUND_PAGE,
} from "./pages";
import { SERVICE_LANDINGS } from "./services";
import { INDUSTRIES } from "./industries";
import { LOCATIONS } from "./locations";
import { CASE_STUDIES } from "./case-studies";
import { ARTICLES } from "./journal";
import type {
  Article,
  CaseStudy,
  HubPage,
  IndustryPage,
  LocationPage,
  ServicePage,
} from "./types";
import type { NavItem } from "./site";
import ru from "./locales/ru";
import th from "./locales/th";
import he from "./locales/he";

/** Shape of `src/content/locales/<locale>/index.ts` (generated by `npm run i18n:sync`). */
type LocaleTranslations = { files: Record<string, unknown> };

const TRANSLATIONS: Record<Exclude<Locale, "en">, LocaleTranslations> = { ru, th, he };

/** English source of every translatable page — also what `scripts/i18n.mjs` extracts. */
export const PAGES = {
  home: HOMEPAGE,
  pillars: HOMEPAGE_PILLARS,
  portfolioItems: HOMEPAGE_PORTFOLIO,
  about: ABOUT_PAGE,
  contact: CONTACT_PAGE,
  portfolio: PORTFOLIO_PAGE,
  caseStudies: CASE_STUDIES_PAGE,
  journal: JOURNAL_PAGE,
  privacy: PRIVACY_PAGE,
  terms: TERMS_PAGE,
  servicesIndex: SERVICES_INDEX,
  industriesIndex: INDUSTRIES_INDEX,
  locationsIndex: LOCATIONS_INDEX,
  editorial: EDITORIAL_PAGE,
  accessibility: ACCESSIBILITY_PAGE,
  notFound: NOT_FOUND_PAGE,
};

/**
 * Every translation file and the English it overlays, keyed by its path
 * under `src/content/locales/<locale>/`. Single source of truth for both the
 * site (below) and `scripts/i18n.mjs` (check/sync/pending/accept/export).
 */
export const TRANSLATION_SOURCES: Record<string, unknown> = {
  "ui.json": UI,
  "pages.json": PAGES,
  "case-studies.json": CASE_STUDIES,
  "journal.json": ARTICLES,
  ...Object.fromEntries(HUBS.map((hub) => [`hubs/${hub.slug}.json`, hub])),
  ...Object.fromEntries(SERVICE_LANDINGS.map((page) => [`services/${page.slug}.json`, page])),
  ...Object.fromEntries(INDUSTRIES.map((page) => [`industries/${page.slug}.json`, page])),
  ...Object.fromEntries(LOCATIONS.map((page) => [`locations/${page.slug}.json`, page])),
};

function memo<T>(build: (locale: Locale) => T): (locale: Locale) => T {
  const cache = new Map<Locale, T>();
  return (locale) => {
    if (!cache.has(locale)) cache.set(locale, build(locale));
    return cache.get(locale)!;
  };
}

function overlay(locale: Locale, file: string): unknown {
  if (locale === DEFAULT_LOCALE) return undefined;
  return TRANSLATIONS[locale as Exclude<Locale, "en">].files[file];
}

export const getUi = memo((locale): UiStrings => localize(UI, overlay(locale, "ui.json")));

export const getPages = memo((locale): typeof PAGES => localize(PAGES, overlay(locale, "pages.json")));

export const getHubs = memo((locale): HubPage[] =>
  HUBS.map((hub) => localize(hub, overlay(locale, `hubs/${hub.slug}.json`)))
);

export const getServiceLandings = memo((locale): ServicePage[] =>
  SERVICE_LANDINGS.map((page) => localize(page, overlay(locale, `services/${page.slug}.json`)))
);

export const getIndustries = memo((locale): IndustryPage[] =>
  INDUSTRIES.map((page) => localize(page, overlay(locale, `industries/${page.slug}.json`)))
);

export const getLocations = memo((locale): LocationPage[] =>
  LOCATIONS.map((page) => localize(page, overlay(locale, `locations/${page.slug}.json`)))
);

export const getCaseStudies = memo((locale): CaseStudy[] =>
  localize(CASE_STUDIES, overlay(locale, "case-studies.json"))
);

export const getArticles = memo((locale): Article[] =>
  localize(ARTICLES, overlay(locale, "journal.json"))
);

export function getHub(slug: string, locale: Locale): HubPage | undefined {
  return getHubs(locale).find((hub) => hub.slug === slug);
}

export function getService(
  hubSlug: string,
  serviceSlug: string,
  locale: Locale
): { hub: HubPage; service: ServicePage } | undefined {
  const hub = getHub(hubSlug, locale);
  const service = hub?.services.find((s) => s.slug === serviceSlug);
  return hub && service ? { hub, service } : undefined;
}

/**
 * Header menu in the proposal's structure (§2): Services (mega-menu in five
 * groups) / Industries / Locations / Work / Journal / About / Contact.
 * Links go to canonical pages; labels come from the target page itself
 * (pageLabelFor), so renaming a page renames its menu entry too.
 */
const SERVICE_GROUPS: { key: keyof UiStrings["nav"]["serviceGroups"]; hrefs: string[] }[] = [
  { key: "advertising", hrefs: ["/advertising", "/advertising/google-ads", "/advertising/meta-ads", "/advertising/performance"] },
  { key: "socialContent", hrefs: ["/social-media", "/social-media/content-creation", "/social-media/reels"] },
  { key: "photoVideo", hrefs: ["/services/commercial-photography", "/video-production/commercial", "/video-production/drone-video", "/food-restaurants/food-photography"] },
  { key: "digital", hrefs: ["/services/digital-marketing", "/services/seo", "/websites-digital/web-design", "/websites-digital/landing-pages"] },
  { key: "creative", hrefs: ["/branding-creative/branding", "/branding-creative/graphic-design", "/branding-creative/creative-direction"] },
];

export const getPrimaryNav = memo((locale): NavItem[] => {
  const ui = getUi(locale);
  const link = (href: string, fallback = href) => ({ label: pageLabelFor(href, locale) ?? fallback, href });
  return [
    {
      label: ui.nav.services,
      href: "/services",
      groups: SERVICE_GROUPS.map((group) => ({
        title: ui.nav.serviceGroups[group.key],
        items: group.hrefs.map((href) => link(href)),
      })),
    },
    {
      label: ui.nav.industries,
      href: "/industries",
      children: getIndustries(locale).map((page) => ({ label: page.navLabel, href: `/industries/${page.slug}` })),
    },
    {
      label: ui.nav.locations,
      href: "/locations",
      children: getLocations(locale).map((page) => ({ label: page.navLabel, href: `/locations/${page.slug}` })),
    },
    {
      label: ui.nav.work,
      href: "/portfolio",
      children: [
        { label: ui.nav.portfolio, href: "/portfolio" },
        { label: ui.nav.caseStudies, href: "/case-studies" },
      ],
    },
    { label: ui.nav.journal, href: "/journal" },
    { label: ui.nav.about, href: "/about" },
    { label: ui.nav.contact, href: "/contact" },
  ];
});

export const getFooterColumns = memo((locale) => {
  const ui = getUi(locale);
  const hubLinks = getHubs(locale).map((hub) => ({ label: hub.navLabel, href: `/${hub.slug}` }));
  return [
    { title: ui.footer.services, links: hubLinks.slice(0, 4) },
    { title: ui.footer.moreServices, links: hubLinks.slice(4) },
    {
      title: ui.footer.industries,
      links: getIndustries(locale).map((page) => ({ label: page.navLabel, href: `/industries/${page.slug}` })),
    },
    {
      title: ui.footer.locations,
      links: [
        ...getLocations(locale).map((page) => ({ label: page.navLabel, href: `/locations/${page.slug}` })),
        { label: ui.nav.allServices, href: "/services" },
      ],
    },
    {
      title: ui.footer.agency,
      links: [
        { label: ui.nav.portfolio, href: "/portfolio" },
        { label: ui.nav.caseStudies, href: "/case-studies" },
        { label: ui.nav.about, href: "/about" },
        { label: ui.nav.journal, href: "/journal" },
      ],
    },
    {
      title: ui.footer.contact,
      links: [
        { label: ui.nav.contact, href: "/contact" },
        { label: ui.cta.startProject, href: "/contact" },
        { label: ui.nav.privacy, href: "/privacy" },
        { label: ui.nav.terms, href: "/terms" },
        { label: ui.nav.editorial, href: "/editorial-policy" },
        { label: ui.nav.accessibility, href: "/accessibility" },
      ],
    },
  ];
});

/**
 * The localized name of the page an internal href points at — lets
 * cross-links (menu, related services, cards) show the page's own current
 * name instead of a copy of it that could drift.
 */
export function pageLabelFor(href: string, locale: Locale): string | undefined {
  const [, first, second] = href.split("/");
  const find = <T extends { slug: string; navLabel: string }>(list: T[]) =>
    list.find((page) => page.slug === second)?.navLabel;
  if (first === "services" && second) return find(getServiceLandings(locale));
  if (first === "industries" && second) return find(getIndustries(locale));
  if (first === "locations" && second) return find(getLocations(locale));
  const hub = getHub(first ?? "", locale);
  if (!hub) return undefined;
  if (!second) return hub.navLabel;
  return hub.services.find((s) => s.slug === second)?.navLabel;
}
