#!/usr/bin/env node
/**
 * Translation maintenance for src/content/locales/<locale>/*.json.
 * English (src/content/**.ts) is the master; see docs/i18n.md.
 *
 * Each translation file has a sidecar in `<locale>/.translated-from/<file>`:
 * for every translated string, a short hash of the English text it was
 * translated from (one sidecar per file, so parallel translators working on
 * different files never overwrite each other's records). So when the
 * English changes, that string shows up as "needs translation" even
 * though the old translation is still there (and still shown).
 *
 *   npm run i18n:check               summary per locale; exits 1 on stale keys
 *                                    or broken {placeholders}
 *   npm run i18n:check -- --verbose  also list every key needing translation
 *   npm run i18n:sync                after editing English: add new keys
 *                                    (pre-filled with English) and drop removed
 *                                    ones; never overwrites a translation
 *   npm run i18n:pending -- <locale> [file]
 *                                    JSON of { key: English } still to translate
 *   npm run i18n:accept -- <locale> [file]
 *                                    after translating: record the current
 *                                    English as the source of those strings
 *   npm run i18n:export              English skeleton → .i18n-source/
 */
import { createJiti } from "jiti";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = path.join(root, "src");
const localesDir = path.join(src, "content", "locales");

const jiti = createJiti(import.meta.url, {
  alias: {
    "@/assets/images": path.join(root, "scripts/lib/i18n-image-stub.ts"),
    "@": src,
  },
});

const { translatableSkeleton } = await jiti.import(path.join(src, "content/localize.ts"));
const { TRANSLATION_SOURCES } = await jiti.import(path.join(src, "content/translations.ts"));
const { LOCALES, DEFAULT_LOCALE } = await jiti.import(path.join(src, "content/i18n.ts"));

/** relative file -> English skeleton (files with nothing to translate yet, e.g. an empty journal, map to {}). */
const SOURCES = Object.fromEntries(
  Object.entries(TRANSLATION_SOURCES).map(([rel, en]) => [rel, translatableSkeleton(en) ?? (Array.isArray(en) ? [] : {})])
);

/** Regenerates src/content/locales/<locale>/index.ts so every translation file is imported. */
function writeLocaleIndex(locale) {
  const rels = Object.keys(SOURCES).sort();
  const ident = (rel) => "f_" + rel.replace(/\.json$/, "").replace(/[^a-zA-Z0-9]/g, "_");
  const body = [
    "// Generated by `npm run i18n:sync` — imports every translation file of this",
    "// locale. Edit the JSON files, not this one.",
    ...rels.map((rel) => `import ${ident(rel)} from "./${rel}";`),
    "",
    "const translations = {",
    "  files: {",
    ...rels.map((rel) => `    "${rel}": ${ident(rel)},`),
    "  } as Record<string, unknown>,",
    "};",
    "",
    "export default translations;",
    "",
  ].join("\n");
  const file = path.join(localesDir, locale, "index.ts");
  if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== body) {
    fs.writeFileSync(file, body);
    console.log(`${locale}/index.ts regenerated`);
  }
}

const placeholders = (s) => (s.match(/\{\w+\}/g) ?? []).sort().join(",");
const isObj = (v) => typeof v === "object" && v !== null && !Array.isArray(v);

/** Walks English vs translation; returns { missing, stale, same, badPlaceholders } as key paths. */
function compare(en, tr, at = "", out = { missing: [], stale: [], same: [], badPlaceholders: [] }) {
  if (typeof en === "string") {
    if (typeof tr !== "string" || !tr.trim()) out.missing.push(at);
    else {
      if (tr === en && /[a-z]{3}/i.test(en)) out.same.push(at);
      if (placeholders(en) !== placeholders(tr)) out.badPlaceholders.push(`${at}  (needs ${placeholders(en) || "none"})`);
    }
    return out;
  }
  const enKeys = Array.isArray(en) ? en.map((_, i) => i) : Object.keys(en ?? {});
  const trContainer = tr ?? (Array.isArray(en) ? [] : {});
  for (const key of enKeys) compare(en[key], trContainer[key], at ? `${at}.${key}` : String(key), out);
  if (isObj(tr) && isObj(en)) for (const key of Object.keys(tr)) if (!(key in en)) out.stale.push(at ? `${at}.${key}` : key);
  if (Array.isArray(tr) && Array.isArray(en) && tr.length > en.length) out.stale.push(`${at}[${en.length}..${tr.length - 1}]`);
  return out;
}

/** English shape, keeping every existing non-empty translated string. */
function merge(en, tr) {
  if (typeof en === "string") return typeof tr === "string" && tr.trim() ? tr : en;
  if (Array.isArray(en)) return en.map((item, i) => merge(item, Array.isArray(tr) ? tr[i] : undefined));
  if (isObj(en)) return Object.fromEntries(Object.entries(en).map(([k, v]) => [k, merge(v, isObj(tr) ? tr[k] : undefined)]));
  return en;
}

/** { "a.b.0.c": "English string" } for every string leaf. */
function flatten(value, at = "", out = {}) {
  if (typeof value === "string") out[at] = value;
  else if (Array.isArray(value)) value.forEach((v, i) => flatten(v, at ? `${at}.${i}` : String(i), out));
  else if (isObj(value)) for (const [k, v] of Object.entries(value)) flatten(v, at ? `${at}.${k}` : k, out);
  return out;
}
const hash = (text) => crypto.createHash("sha1").update(text).digest("hex").slice(0, 10);
const sourceFile = (locale, rel) => path.join(localesDir, locale, ".translated-from", rel);

/** Keys whose English has no recorded translation or changed since it was translated. */
function pendingKeys(locale, rel, skeleton, translation) {
  const recorded = readJson(sourceFile(locale, rel)) ?? {};
  const tr = flatten(translation ?? {});
  return Object.entries(flatten(skeleton))
    .filter(([key, en]) => /\p{L}{2}/u.test(en) && (!tr[key]?.trim() || recorded[key] !== hash(en)))
    .map(([key]) => key);
}

const readJson = (file) => (fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : undefined);
const writeJson = (file, data) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + "\n");
};

const targetLocales = LOCALES.filter((l) => l !== DEFAULT_LOCALE);
const command = process.argv[2] ?? "check";

const [argLocale, argFile] = process.argv.slice(3).filter((a) => !a.startsWith("--"));
function selected() {
  const locales = argLocale ? [argLocale] : targetLocales;
  const files = argFile ? [argFile] : Object.keys(SOURCES);
  for (const l of locales) if (!targetLocales.includes(l)) throw new Error(`Unknown locale "${l}"`);
  for (const f of files) if (!SOURCES[f]) throw new Error(`Unknown file "${f}" — one of: ${Object.keys(SOURCES).join(", ")}`);
  return { locales, files };
}

if (command === "export") {
  const outDir = path.join(root, ".i18n-source");
  for (const [rel, skeleton] of Object.entries(SOURCES)) writeJson(path.join(outDir, rel), skeleton);
  console.log(`English source written to ${path.relative(root, outDir)}/`);
} else if (command === "sync") {
  for (const locale of targetLocales) {
    for (const [rel, skeleton] of Object.entries(SOURCES)) {
      const file = path.join(localesDir, locale, rel);
      const before = readJson(file);
      const after = merge(skeleton, before);
      if (JSON.stringify(before) !== JSON.stringify(after)) {
        const { missing, stale } = compare(skeleton, before);
        writeJson(file, after);
        console.log(`${locale}/${rel}: +${missing.length} new (English placeholder text), -${stale.length} removed`);
      }
    }
    writeLocaleIndex(locale);
    // Drop hashes for keys English no longer has, and sidecars of removed files.
    for (const rel of Object.keys(SOURCES)) {
      const recorded = readJson(sourceFile(locale, rel));
      if (!recorded) continue;
      const live = flatten(SOURCES[rel]);
      for (const key of Object.keys(recorded)) if (!(key in live)) delete recorded[key];
      writeJson(sourceFile(locale, rel), recorded);
    }
  }
  console.log("Synced. `npm run i18n:check -- --verbose` lists what needs translating.");
} else if (command === "pending") {
  const { locales, files } = selected();
  const out = {};
  for (const locale of locales)
    for (const rel of files) {
      const keys = pendingKeys(locale, rel, SOURCES[rel], readJson(path.join(localesDir, locale, rel)));
      if (keys.length) {
        const en = flatten(SOURCES[rel]);
        out[`${locale}/${rel}`] = Object.fromEntries(keys.map((k) => [k, en[k]]));
      }
    }
  console.log(JSON.stringify(out, null, 2));
} else if (command === "accept") {
  const { locales, files } = selected();
  for (const locale of locales) {
    for (const rel of files) {
      const tr = flatten(readJson(path.join(localesDir, locale, rel)) ?? {});
      const recorded = readJson(sourceFile(locale, rel)) ?? {};
      for (const [key, en] of Object.entries(flatten(SOURCES[rel]))) if (tr[key]?.trim()) recorded[key] = hash(en);
      writeJson(sourceFile(locale, rel), recorded);
    }
    console.log(`${locale}: recorded the current English as the source of ${files.length} file(s)`);
  }
} else if (command === "check") {
  let errors = 0;
  for (const locale of targetLocales) {
    let pending = 0;
    for (const [rel, skeleton] of Object.entries(SOURCES)) {
      const translation = readJson(path.join(localesDir, locale, rel));
      const r = compare(skeleton, translation);
      const todo = pendingKeys(locale, rel, skeleton, translation);
      pending += todo.length;
      const show = (label, list) => list.length && console.log(`  ${locale}/${rel} — ${label} (${list.length}):\n${list.slice(0, 15).map((k) => `      ${k}`).join("\n")}${list.length > 15 ? "\n      …" : ""}`);
      show("STALE keys, not in English any more", r.stale);
      show("BROKEN placeholders", r.badPlaceholders);
      if (process.argv.includes("--verbose")) show("needs translation (new or English changed)", todo);
      errors += r.stale.length + r.badPlaceholders.length;
    }
    console.log(`${locale}: ${pending} string(s) need translation (new, or English changed since translated)`);
  }
  if (errors) {
    console.error(`\n${errors} error(s) — run \`npm run i18n:sync\` for stale keys, fix placeholders by hand.`);
    process.exit(1);
  }
} else {
  console.error(`Unknown command "${command}" — use check, sync, pending, accept or export.`);
  process.exit(1);
}
